Mod Remove: MCMultiPart-2.0.0.jar Crash: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MCMultiPart (mcmultipart) Caused by: java.lang.NoSuchMethodError: net.minecraft.block.properties.PropertyBool.create(Ljava/lang/String;)Lnet/minecraft/block/properties/PropertyBool; 	at mcmultipart.block.BlockMultipartContainer.<clinit>(BlockMultipartContainer.java:58) 	at mcmultipart.MCMultiPart.preInit(MCMultiPart.java:114)